### ISSUE TITLE
addCharacter addon

### ISSUE THREAD

**Issue by supermoaaa** [UPBGE/blender-addons#1]
[AddCharacter.zip](https://github.com/UPBGE/blender-addons/files/2053232/AddCharacter.zip)

The first version of addCharater addon work fine i think i can go in official upbge

**Comment by lordloki** [comment]
Hi @supermoaaa 
Yesterday I tested your addon. I see the following things that can be improved:
- Replace always sensor with Mouse sensors type movement
- In Mouse Look actuators sensibility is better to 0.5
- Motion actuator movement better 0.2 than 1.0
- For Add fly camera, the motion movement for W&S, or UP&DOWN keys should be -0.2/0.2 for Local axis Z.
- Replace cilinder body by a cone. This way when we select the camera view we can see where we look at the beginning.
- Additionally we can create a new wiki page in this repository as basic documentation and reference it from addon

**Comment by supermoaaa** [comment]
Replace always sensor by Mouse sensor ok

add options for keys and mouse sensitivity

add a cone collision bounds for fly cam

perhaps it's better to make a new option for that i don't now
[AddCharacter.zip](https://github.com/UPBGE/blender-addons/files/2059959/AddCharacter.zip)

**Comment by lordloki** [comment]
Commited with little cosmetic changes. Supermoaaa I think that you already have commit rights if you want to modify the addon.
