### ISSUE TITLE
bge_bricknodes fails to load; ops.py is missing classes

### ISSUE THREAD

**Issue by clarence112** [UPBGE/blender-addons#3]
![image](https://user-images.githubusercontent.com/20058567/145454080-391343b6-7543-4e8f-aeb6-2df0f487c67d.png)

The missing classes appear to have been removed in [this commit.](https://github.com/UPBGE/blender-addons/commit/8f1ead02787a40104293ab9dce22ddc4a2176f64#)

**Comment by clarence112** [comment]
Simply copy-pasting the missing classes (ui.py was also affected) seems to have fixed things. Can't say whether or not that's a good solution, though.

**Comment by lordloki** [comment]
I just checked and the files in bge_bricknodes folder under blender-addons match the files that are in https://github.com/IzaZed/bricky-nodes

@IzaZed Zed could you take a look? Thanks in advance

**Comment by IzaZed** [comment]
Sorry for the late answer, I'll check now

**Comment by IzaZed** [comment]
should be working now

**Comment by lordloki** [comment]
Thanks for the fix. Closing the issue as I just synchronize the repository.
