### ISSUE TITLE
`io_scene_gltf2` no longer working with the current UPBGE master

### ISSUE THREAD

**Issue by mysticfall** [UPBGE/blender-addons#8]
GLTF2 import is no longer working in the current UPBGE master (`73346754b9`) due to changes in the core API. The stacktrace is as follows:
```
  File "/usr/share/upbge/4.1/scripts/addons/io_scene_gltf2/blender/imp/gltf2_blender_mesh.py", line 482, in do_primitives
    mesh.create_normals_split()
    ^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Mesh' object has no attribute 'create_normals_split'
```

The upstream contains [the commit](https://github.com/blender/blender-addons/commit/b1fbf73a08cfb68b14bb328590a9bb6602d96916) that appears to be addressing this issue.

**Comment by lordloki** [comment]
I just update the addons. Thanks for reporting.

**Comment by mysticfall** [comment]
Thanks much for the quick resolution! :)
